name = "Atom One Dark"

[colors]
foreground = "#abb2bf"
background = "#21252b"
cursor = "#abb2bf"
selection = "#323844"

[colors.ansi]
black = "#21252b"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#767676"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"
