name = "Bluloco Light"

[colors]
foreground = "#373a41"
background = "#f9f9f9"
cursor = "#f32759"
selection = "#daf0ff"

[colors.ansi]
black = "#373a41"
red = "#d52753"
green = "#23974a"
yellow = "#df631c"
blue = "#275fe4"
magenta = "#823ff1"
cyan = "#27618d"
white = "#babbc2"

[colors.bright]
black = "#676a77"
red = "#ff6480"
green = "#3cbc66"
yellow = "#c5a332"
blue = "#0099e1"
magenta = "#ce33c0"
cyan = "#6d93bb"
white = "#d3d3d3"
