name = "Cobalt Next Minimal"

[colors]
foreground = "#d8dee9"
background = "#0f1c23"
cursor = "#5fb3b3"
selection = "#5fb3b3"

[colors.ansi]
black = "#343d46"
red = "#ed6f7d"
green = "#99c794"
yellow = "#fac863"
blue = "#5a9bcf"
magenta = "#c5a5c5"
cyan = "#5fb3b3"
white = "#d8dee9"

[colors.bright]
black = "#65737e"
red = "#d6838c"
green = "#c1dcbe"
yellow = "#ffde9b"
blue = "#8abee7"
magenta = "#edcded"
cyan = "#9be2e2"
white = "#ffffff"
