name = "Cobalt Next"

[colors]
foreground = "#d8dee9"
background = "#1b2b34"
cursor = "#fac863"
selection = "#4f5b66"

[colors.ansi]
black = "#000000"
red = "#ed5f7d"
green = "#99c794"
yellow = "#fac863"
blue = "#5a9bcf"
magenta = "#c5a5c5"
cyan = "#5fb3b3"
white = "#d8dee9"

[colors.bright]
black = "#65737e"
red = "#d6838c"
green = "#c1dcbe"
yellow = "#ffde9b"
blue = "#8abee7"
magenta = "#edcded"
cyan = "#9be2e2"
white = "#ffffff"
