name = "Floraverse"

[colors]
foreground = "#dbd1b9"
background = "#0e0d15"
cursor = "#bbbbbb"
selection = "#f3e0b8"

[colors.ansi]
black = "#08002e"
red = "#64002c"
green = "#5d731a"
yellow = "#cd751c"
blue = "#1d6da1"
magenta = "#b7077e"
cyan = "#42a38c"
white = "#f3e0b8"

[colors.bright]
black = "#331e4d"
red = "#d02063"
green = "#b4ce59"
yellow = "#fac357"
blue = "#40a4cf"
magenta = "#f12aae"
cyan = "#62caa8"
white = "#fff5db"
