name = "Forest Blue"

[colors]
foreground = "#e2d8cd"
background = "#051519"
cursor = "#9e9ecb"
selection = "#4d4d4d"

[colors.ansi]
black = "#333333"
red = "#f8818e"
green = "#92d3a2"
yellow = "#1a8e63"
blue = "#8ed0ce"
magenta = "#5e468c"
cyan = "#31658c"
white = "#e2d8cd"

[colors.bright]
black = "#3d3d3d"
red = "#fb3d66"
green = "#6bb48d"
yellow = "#30c85a"
blue = "#39a7a2"
magenta = "#7e62b3"
cyan = "#6096bf"
white = "#e2d8cd"
