name = "Horizon Bright"

[colors]
foreground = "#16161c"
background = "#fbf0ee"
cursor = "#f2d0c5"
selection = "#f2d0c5"

[colors.ansi]
black = "#16161c"
red = "#e95678"
green = "#29d398"
yellow = "#fab795"
blue = "#26bbd9"
magenta = "#ee64ae"
cyan = "#59e3e3"
white = "#fdf0ed"

[colors.bright]
black = "#1a1c23"
red = "#ec6a88"
green = "#3fdaa4"
yellow = "#fbc3a7"
blue = "#3fc6de"
magenta = "#f075b7"
cyan = "#6be6e6"
white = "#fff3f0"
