name = "Monokai Pro Ristretto"

[colors]
foreground = "#fff1f3"
background = "#2c2525"
cursor = "#c3b7b8"
selection = "#5b5353"

[colors.ansi]
black = "#2c2525"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#f38d70"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#fff1f3"

[colors.bright]
black = "#72696a"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#f38d70"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#fff1f3"
