name = "One Half Dark"

[colors]
foreground = "#dcdfe4"
background = "#282c34"
cursor = "#a3b3cc"
selection = "#474e5d"

[colors.ansi]
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#dcdfe4"

[colors.bright]
black = "#5d677a"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#dcdfe4"
