name = "Poimandres Darker"

[colors]
foreground = "#a6accd"
background = "#16161e"
cursor = "#ffffff"
selection = "#a6accd"

[colors.ansi]
black = "#16161e"
red = "#d0679d"
green = "#5de4c7"
yellow = "#fffac2"
blue = "#89ddff"
magenta = "#fcc5e9"
cyan = "#add7ff"
white = "#ffffff"

[colors.bright]
black = "#a6accd"
red = "#d0679d"
green = "#5de4c7"
yellow = "#fffac2"
blue = "#add7ff"
magenta = "#fae4fc"
cyan = "#89ddff"
white = "#ffffff"
