name = "Tomorrow Night Blue"

[colors]
foreground = "#ffffff"
background = "#002451"
cursor = "#ffffff"
selection = "#003f8e"

[colors.ansi]
black = "#000000"
red = "#ff9da4"
green = "#d1f1a9"
yellow = "#ffeead"
blue = "#bbdaff"
magenta = "#ebbbff"
cyan = "#99ffff"
white = "#ffffff"

[colors.bright]
black = "#000000"
red = "#ff9da4"
green = "#d1f1a9"
yellow = "#ffeead"
blue = "#bbdaff"
magenta = "#ebbbff"
cyan = "#99ffff"
white = "#ffffff"
