name = "Under The Sea"

[colors]
foreground = "#ffffff"
background = "#011116"
cursor = "#4afcd6"
selection = "#415555"

[colors.ansi]
black = "#022026"
red = "#b2302d"
green = "#00a941"
yellow = "#59819c"
blue = "#459a86"
magenta = "#00599d"
cyan = "#5d7e19"
white = "#405555"

[colors.bright]
black = "#384451"
red = "#ff4242"
green = "#2aea5e"
yellow = "#8ed4fd"
blue = "#61d5ba"
magenta = "#1298ff"
cyan = "#98d028"
white = "#58fbd6"
