name = "Wilmersdorf"

[colors]
foreground = "#c6c6c6"
background = "#282b33"
cursor = "#7ebebd"
selection = "#1f2024"

[colors.ansi]
black = "#34373e"
red = "#e06383"
green = "#7ebebd"
yellow = "#cccccc"
blue = "#a6c1e0"
magenta = "#e1c1ee"
cyan = "#5b94ab"
white = "#ababab"

[colors.bright]
black = "#434750"
red = "#fa7193"
green = "#8fd7d6"
yellow = "#d1dfff"
blue = "#b2cff0"
magenta = "#efccfd"
cyan = "#69abc5"
white = "#d3d3d3"
