name = "Zenburned"

[colors]
foreground = "#f0e4cf"
background = "#404040"
cursor = "#f3eadb"
selection = "#746956"

[colors.ansi]
black = "#404040"
red = "#e3716e"
green = "#819b69"
yellow = "#b77e64"
blue = "#6099c0"
magenta = "#b279a7"
cyan = "#66a5ad"
white = "#f0e4cf"

[colors.bright]
black = "#625a5b"
red = "#ec8685"
green = "#8bae68"
yellow = "#d68c67"
blue = "#61abda"
magenta = "#cf86c1"
cyan = "#65b8c1"
white = "#c0ab86"
